# Generated by Django 3.2.5 on 2021-12-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='image1', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
